import java.util.LinkedHashMap;
import java.util.Map;

public class MonedaData {

    public static Map<Integer, String[]> obtenerListadoMonedas() {
        Map<Integer, String[]> monedas = new LinkedHashMap<>();
        monedas.put(1, new String[]{"AED", "UAE Dirham", "United Arab Emirates"});
        monedas.put(2, new String[]{"AFN", "Afghan Afghani", "Afghanistan"});
        monedas.put(3, new String[]{"ALL", "Albanian Lek", "Albania"});
        monedas.put(4, new String[]{"AMD", "Armenian Dram", "Armenia"});
        monedas.put(5, new String[]{"ANG", "Netherlands Antillian Guilder", "Netherlands Antilles"});
        monedas.put(6, new String[]{"AOA", "Angolan Kwanza", "Angola"});
        monedas.put(7, new String[]{"ARS", "Argentine Peso", "Argentina"});
        monedas.put(8, new String[]{"AUD", "Australian Dollar", "Australia"});
        monedas.put(9, new String[]{"AWG", "Aruban Florin", "Aruba"});
        monedas.put(10, new String[]{"AZN", "Azerbaijani Manat", "Azerbaijan"});
        monedas.put(11, new String[]{"BAM", "Bosnia and Herzegovina Mark", "Bosnia and Herzegovina"});
        monedas.put(12, new String[]{"BBD", "Barbados Dollar", "Barbados"});
        monedas.put(13, new String[]{"BDT", "Bangladeshi Taka", "Bangladesh"});
        monedas.put(14, new String[]{"BGN", "Bulgarian Lev", "Bulgaria"});
        monedas.put(15, new String[]{"BHD", "Bahraini Dinar", "Bahrain"});
        monedas.put(16, new String[]{"BIF", "Burundian Franc", "Burundi"});
        monedas.put(17, new String[]{"BMD", "Bermudian Dollar", "Bermuda"});
        monedas.put(18, new String[]{"BND", "Brunei Dollar", "Brunei"});
        monedas.put(19, new String[]{"BOB", "Bolivian Boliviano", "Bolivia"});
        monedas.put(20, new String[]{"BRL", "Brazilian Real", "Brazil"});
        monedas.put(21, new String[]{"BSD", "Bahamian Dollar", "Bahamas"});
        monedas.put(22, new String[]{"BTN", "Bhutanese Ngultrum", "Bhutan"});
        monedas.put(23, new String[]{"BWP", "Botswana Pula", "Botswana"});
        monedas.put(24, new String[]{"BYN", "Belarusian Ruble", "Belarus"});
        monedas.put(25, new String[]{"BZD", "Belize Dollar", "Belize"});
        monedas.put(26, new String[]{"CAD", "Canadian Dollar", "Canada"});
        monedas.put(27, new String[]{"CDF", "Congolese Franc", "Democratic Republic of the Congo"});
        monedas.put(28, new String[]{"CHF", "Swiss Franc", "Switzerland"});
        monedas.put(29, new String[]{"CLP", "Chilean Peso", "Chile"});
        monedas.put(30, new String[]{"CNY", "Chinese Renminbi", "China"});
        monedas.put(31, new String[]{"COP", "Colombian Peso", "Colombia"});
        monedas.put(32, new String[]{"CRC", "Costa Rican Colon", "Costa Rica"});
        monedas.put(33, new String[]{"CUP", "Cuban Peso", "Cuba"});
        monedas.put(34, new String[]{"CVE", "Cape Verdean Escudo", "Cape Verde"});
        monedas.put(35, new String[]{"CZK", "Czech Koruna", "Czech Republic"});
        monedas.put(36, new String[]{"DJF", "Djiboutian Franc", "Djibouti"});
        monedas.put(37, new String[]{"DKK", "Danish Krone", "Denmark"});
        monedas.put(38, new String[]{"DOP", "Dominican Peso", "Dominican Republic"});
        monedas.put(39, new String[]{"DZD", "Algerian Dinar", "Algeria"});
        monedas.put(40, new String[]{"EGP", "Egyptian Pound", "Egypt"});
        monedas.put(41, new String[]{"ERN", "Eritrean Nakfa", "Eritrea"});
        monedas.put(42, new String[]{"ETB", "Ethiopian Birr", "Ethiopia"});
        monedas.put(43, new String[]{"EUR", "Euro", "European Union"});
        monedas.put(44, new String[]{"FJD", "Fiji Dollar", "Fiji"});
        monedas.put(45, new String[]{"FKP", "Falkland Islands Pound", "Falkland Islands"});
        monedas.put(46, new String[]{"FOK", "Faroese Króna", "Faroe Islands"});
        monedas.put(47, new String[]{"GBP", "Pound Sterling", "United Kingdom"});
        monedas.put(48, new String[]{"GEL", "Georgian Lari", "Georgia"});
        monedas.put(49, new String[]{"GGP", "Guernsey Pound", "Guernsey"});
        monedas.put(50, new String[]{"GHS", "Ghanaian Cedi", "Ghana"});
        monedas.put(51, new String[]{"GIP", "Gibraltar Pound", "Gibraltar"});
        monedas.put(52, new String[]{"GMD", "Gambian Dalasi", "The Gambia"});
        monedas.put(53, new String[]{"GNF", "Guinean Franc", "Guinea"});
        monedas.put(54, new String[]{"GTQ", "Guatemalan Quetzal", "Guatemala"});
        monedas.put(55, new String[]{"GYD", "Guyanese Dollar", "Guyana"});
        monedas.put(56, new String[]{"HKD", "Hong Kong Dollar", "Hong Kong"});
        monedas.put(57, new String[]{"HNL", "Honduran Lempira", "Honduras"});
        monedas.put(58, new String[]{"HRK", "Croatian Kuna", "Croatia"});
        monedas.put(59, new String[]{"HTG", "Haitian Gourde", "Haiti"});
        monedas.put(60, new String[]{"HUF", "Hungarian Forint", "Hungary"});
        monedas.put(61, new String[]{"IDR", "Indonesian Rupiah", "Indonesia"});
        monedas.put(62, new String[]{"ILS", "Israeli New Shekel", "Israel"});
        monedas.put(63, new String[]{"IMP", "Manx Pound", "Isle of Man"});
        monedas.put(64, new String[]{"INR", "Indian Rupee", "India"});
        monedas.put(65, new String[]{"IQD", "Iraqi Dinar", "Iraq"});
        monedas.put(66, new String[]{"IRR", "Iranian Rial", "Iran"});
        monedas.put(67, new String[]{"ISK", "Icelandic Króna", "Iceland"});
        monedas.put(68, new String[]{"JEP", "Jersey Pound", "Jersey"});
        monedas.put(69, new String[]{"JMD", "Jamaican Dollar", "Jamaica"});
        monedas.put(70, new String[]{"JOD", "Jordanian Dinar", "Jordan"});
        monedas.put(71, new String[]{"JPY", "Japanese Yen", "Japan"});
        monedas.put(72, new String[]{"KES", "Kenyan Shilling", "Kenya"});
        monedas.put(73, new String[]{"KGS", "Kyrgyzstani Som", "Kyrgyzstan"});
        monedas.put(74, new String[]{"KHR", "Cambodian Riel", "Cambodia"});
        monedas.put(75, new String[]{"KID", "Kiribati Dollar", "Kiribati"});
        monedas.put(76, new String[]{"KMF", "Comorian Franc", "Comoros"});
        monedas.put(77, new String[]{"KRW", "South Korean Won", "South Korea"});
        monedas.put(78, new String[]{"KWD", "Kuwaiti Dinar", "Kuwait"});
        monedas.put(79, new String[]{"KYD", "Cayman Islands Dollar", "Cayman Islands"});
        monedas.put(80, new String[]{"KZT", "Kazakhstani Tenge", "Kazakhstan"});
        monedas.put(81, new String[]{"LAK", "Lao Kip", "Laos"});
        monedas.put(82, new String[]{"LBP", "Lebanese Pound", "Lebanon"});
        monedas.put(83, new String[]{"LKR", "Sri Lanka Rupee", "Sri Lanka"});
        monedas.put(84, new String[]{"LRD", "Liberian Dollar", "Liberia"});
        monedas.put(85, new String[]{"LSL", "Lesotho Loti", "Lesotho"});
        monedas.put(86, new String[]{"LYD", "Libyan Dinar", "Libya"});
        monedas.put(87, new String[]{"MAD", "Moroccan Dirham", "Morocco"});
        monedas.put(88, new String[]{"MDL", "Moldovan Leu", "Moldova"});
        monedas.put(89, new String[]{"MGA", "Malagasy Ariary", "Madagascar"});
        monedas.put(90, new String[]{"MKD", "Macedonian Denar", "North Macedonia"});
        monedas.put(91, new String[]{"MMK", "Burmese Kyat", "Myanmar"});
        monedas.put(92, new String[]{"MNT", "Mongolian Tögrög", "Mongolia"});
        monedas.put(93, new String[]{"MOP", "Macanese Pataca", "Macau"});
        monedas.put(94, new String[]{"MRU", "Mauritanian Ouguiya", "Mauritania"});
        monedas.put(95, new String[]{"MUR", "Mauritian Rupee", "Mauritius"});
        monedas.put(96, new String[]{"MVR", "Maldivian Rufiyaa", "Maldives"});
        monedas.put(97, new String[]{"MWK", "Malawian Kwacha", "Malawi"});
        monedas.put(98, new String[]{"MXN", "Mexican Peso", "Mexico"});
        monedas.put(99, new String[]{"MYR", "Malaysian Ringgit", "Malaysia"});
        monedas.put(100, new String[]{"MZN", "Mozambican Metical", "Mozambique"});
        monedas.put(101, new String[]{"NAD", "Namibian Dollar", "Namibia"});
        monedas.put(102, new String[]{"NGN", "Nigerian Naira", "Nigeria"});
        monedas.put(103, new String[]{"NIO", "Nicaraguan Córdoba", "Nicaragua"});
        monedas.put(104, new String[]{"NOK", "Norwegian Krone", "Norway"});
        monedas.put(105, new String[]{"NPR", "Nepalese Rupee", "Nepal"});
        monedas.put(106, new String[]{"NZD", "New Zealand Dollar", "New Zealand"});
        monedas.put(107, new String[]{"OMR", "Omani Rial", "Oman"});
        monedas.put(108, new String[]{"PAB", "Panamanian Balboa", "Panama"});
        monedas.put(109, new String[]{"PEN", "Peruvian Sol", "Peru"});
        monedas.put(110, new String[]{"PGK", "Papua New Guinean Kina", "Papua New Guinea"});
        monedas.put(111, new String[]{"PHP", "Philippine Peso", "Philippines"});
        monedas.put(112, new String[]{"PKR", "Pakistani Rupee", "Pakistan"});
        monedas.put(113, new String[]{"PLN", "Polish Złoty", "Poland"});
        monedas.put(114, new String[]{"PYG", "Paraguayan Guaraní", "Paraguay"});
        monedas.put(115, new String[]{"QAR", "Qatari Riyal", "Qatar"});
        monedas.put(116, new String[]{"RON", "Romanian Leu", "Romania"});
        monedas.put(117, new String[]{"RSD", "Serbian Dinar", "Serbia"});
        monedas.put(118, new String[]{"RUB", "Russian Ruble", "Russia"});
        monedas.put(119, new String[]{"RWF", "Rwandan Franc", "Rwanda"});
        monedas.put(120, new String[]{"SAR", "Saudi Riyal", "Saudi Arabia"});
        monedas.put(121, new String[]{"SBD", "Solomon Islands Dollar", "Solomon Islands"});
        monedas.put(122, new String[]{"SCR", "Seychellois Rupee", "Seychelles"});
        monedas.put(123, new String[]{"SDG", "Sudanese Pound", "Sudan"});
        monedas.put(124, new String[]{"SEK", "Swedish Krona", "Sweden"});
        monedas.put(125, new String[]{"SGD", "Singapore Dollar", "Singapore"});
        monedas.put(126, new String[]{"SHP", "Saint Helena Pound", "Saint Helena"});
        monedas.put(127, new String[]{"SLE", "Sierra Leonean Leone", "Sierra Leone"});
        monedas.put(128, new String[]{"SOS", "Somali Shilling", "Somalia"});
        monedas.put(129, new String[]{"SRD", "Surinamese Dollar", "Suriname"});
        monedas.put(130, new String[]{"SSP", "South Sudanese Pound", "South Sudan"});
        monedas.put(131, new String[]{"STN", "São Tomé and Príncipe Dobra", "São Tomé and Príncipe"});
        monedas.put(132, new String[]{"SYP", "Syrian Pound", "Syria"});
        monedas.put(133, new String[]{"SZL", "Eswatini Lilangeni", "Eswatini"});
        monedas.put(134, new String[]{"THB", "Thai Baht", "Thailand"});
        monedas.put(135, new String[]{"TJS", "Tajikistani Somoni", "Tajikistan"});
        monedas.put(136, new String[]{"TMT", "Turkmenistan Manat", "Turkmenistan"});
        monedas.put(137, new String[]{"TND", "Tunisian Dinar", "Tunisia"});
        monedas.put(138, new String[]{"TOP", "Tongan Paʻanga", "Tonga"});
        monedas.put(139, new String[]{"TRY", "Turkish Lira", "Turkey"});
        monedas.put(140, new String[]{"TTD", "Trinidad and Tobago Dollar", "Trinidad and Tobago"});
        monedas.put(141, new String[]{"TVD", "Tuvaluan Dollar", "Tuvalu"});
        monedas.put(142, new String[]{"TWD", "New Taiwan Dollar", "Taiwan"});
        monedas.put(143, new String[]{"TZS", "Tanzanian Shilling", "Tanzania"});
        monedas.put(144, new String[]{"UAH", "Ukrainian Hryvnia", "Ukraine"});
        monedas.put(145, new String[]{"UGX", "Ugandan Shilling", "Uganda"});
        monedas.put(146, new String[]{"USD", "United States Dollar", "United States"});
        monedas.put(147, new String[]{"UYU", "Uruguayan Peso", "Uruguay"});
        monedas.put(148, new String[]{"UZS", "Uzbekistani So'm", "Uzbekistan"});
        monedas.put(149, new String[]{"VES", "Venezuelan Bolívar Soberano", "Venezuela"});
        monedas.put(150, new String[]{"VND", "Vietnamese Đồng", "Vietnam"});
        monedas.put(151, new String[]{"VUV", "Vanuatu Vatu", "Vanuatu"});
        monedas.put(152, new String[]{"WST", "Samoan Tālā", "Samoa"});
        monedas.put(153, new String[]{"XAF", "Central African CFA Franc", "CEMAC"});
        monedas.put(154, new String[]{"XCD", "East Caribbean Dollar", "Organisation of Eastern Caribbean States"});
        monedas.put(155, new String[]{"XDR", "Special Drawing Rights", "International Monetary Fund"});
        monedas.put(156, new String[]{"XOF", "West African CFA franc", "CFA"});
        monedas.put(157, new String[]{"XPF", "CFP Franc", "Collectivités d'Outre-Mer"});
        monedas.put(158, new String[]{"YER", "Yemeni Rial", "Yemen"});
        monedas.put(159, new String[]{"ZAR", "South African Rand", "South Africa"});
        monedas.put(160, new String[]{"ZMW", "Zambian Kwacha", "Zambia"});
        monedas.put(161, new String[]{"ZWL", "Zimbabwean Dollar", "Zimbabwe"});

        return monedas;
    }
}
